# Configuración de Railway para SMART_STUDENT
# Este archivo anula la detección automática del tipo de proyecto

[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

# Comando de inicio personalizado - esencial para ejecutar nuestro script
[deploy]
startCommand = "cd /app && python emergency_start_railway.py"
restartPolicyType = "on_failure"