# Configuración de Railway para SMART_STUDENT
# Este archivo anula la detección automática del tipo de proyecto

[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

# Comando de inicio personalizado - sin usar cd
[deploy]
startCommand = "python emergency_start_railway.py"
restartPolicyType = "on_failure"