graph LR
    N1_365["sistema respiratorio"]
    style N1_365 fill:#f9f,stroke:#333,stroke-width:2px
    N2_774["Estructura"]
    N1_365 --> N2_774
    style N2_774 fill:#ccf,stroke:#333,stroke-width:2px
    N3_112["Nariz"]
    N2_774 --> N3_112
    style N3_112 fill:#9cf,stroke:#333,stroke-width:2px
    N4_963["Faringe"]
    N2_774 --> N4_963
    style N4_963 fill:#9cf,stroke:#333,stroke-width:2px
    N5_286["Laringe"]
    N2_774 --> N5_286
    style N5_286 fill:#9cf,stroke:#333,stroke-width:2px
    N6_650["Tráquea"]
    N2_774 --> N6_650
    style N6_650 fill:#9cf,stroke:#333,stroke-width:2px
    N7_229["Bronquios"]
    N2_774 --> N7_229
    style N7_229 fill:#9cf,stroke:#333,stroke-width:2px
    N8_943["Pulmones"]
    N2_774 --> N8_943
    style N8_943 fill:#9cf,stroke:#333,stroke-width:2px
    N9_517["Función"]
    N1_365 --> N9_517
    style N9_517 fill:#ccf,stroke:#333,stroke-width:2px
    N10_507["Intercambio de gases"]
    N9_517 --> N10_507
    style N10_507 fill:#9cf,stroke:#333,stroke-width:2px
    N11_181["Oxigenación de la sangre"]
    N9_517 --> N11_181
    style N11_181 fill:#9cf,stroke:#333,stroke-width:2px
    N12_570["Eliminación de CO2"]
    N9_517 --> N12_570
    style N12_570 fill:#9cf,stroke:#333,stroke-width:2px
    N13_179["Mecanismos"]
    N1_365 --> N13_179
    style N13_179 fill:#ccf,stroke:#333,stroke-width:2px
    N14_912["Inspiración"]
    N13_179 --> N14_912
    style N14_912 fill:#9cf,stroke:#333,stroke-width:2px
    N15_679["Espiración"]
    N13_179 --> N15_679
    style N15_679 fill:#9cf,stroke:#333,stroke-width:2px
    N16_865["Control nervioso"]
    N13_179 --> N16_865
    style N16_865 fill:#9cf,stroke:#333,stroke-width:2px
    N17_729["Enfermedades"]
    N1_365 --> N17_729
    style N17_729 fill:#ccf,stroke:#333,stroke-width:2px
    N18_355["Asma"]
    N17_729 --> N18_355
    style N18_355 fill:#9cf,stroke:#333,stroke-width:2px
    N19_976["Bronquitis"]
    N17_729 --> N19_976
    style N19_976 fill:#9cf,stroke:#333,stroke-width:2px
    N20_878["Neumonía"]
    N17_729 --> N20_878
    style N20_878 fill:#9cf,stroke:#333,stroke-width:2px
    N21_658["EPOC"]
    N17_729 --> N21_658
    style N21_658 fill:#9cf,stroke:#333,stroke-width:2px
    N22_540["Factores de riesgo"]
    N1_365 --> N22_540
    style N22_540 fill:#ccf,stroke:#333,stroke-width:2px
    N23_498["Tabaquismo"]
    N22_540 --> N23_498
    style N23_498 fill:#9cf,stroke:#333,stroke-width:2px
    N24_726["Contaminación"]
    N22_540 --> N24_726
    style N24_726 fill:#9cf,stroke:#333,stroke-width:2px
    N25_759["Infecciones"]
    N22_540 --> N25_759
    style N25_759 fill:#9cf,stroke:#333,stroke-width:2px