graph LR
    N1_485["sistema respiratorio"]
    style N1_485 fill:#f9f,stroke:#333,stroke-width:2px
    N2_729["Estructura"]
    N1_485 --> N2_729
    style N2_729 fill:#ccf,stroke:#333,stroke-width:2px
    N3_173["Nariz"]
    N2_729 --> N3_173
    style N3_173 fill:#9cf,stroke:#333,stroke-width:2px
    N4_144["Faringe"]
    N2_729 --> N4_144
    style N4_144 fill:#9cf,stroke:#333,stroke-width:2px
    N5_377["Laringe"]
    N2_729 --> N5_377
    style N5_377 fill:#9cf,stroke:#333,stroke-width:2px
    N6_542["Tráquea"]
    N2_729 --> N6_542
    style N6_542 fill:#9cf,stroke:#333,stroke-width:2px
    N7_507["Bronquios"]
    N2_729 --> N7_507
    style N7_507 fill:#9cf,stroke:#333,stroke-width:2px
    N8_830["Pulmones"]
    N2_729 --> N8_830
    style N8_830 fill:#9cf,stroke:#333,stroke-width:2px
    N9_623["Función"]
    N1_485 --> N9_623
    style N9_623 fill:#ccf,stroke:#333,stroke-width:2px
    N10_209["Intercambio de gases"]
    N9_623 --> N10_209
    style N10_209 fill:#9cf,stroke:#333,stroke-width:2px
    N11_695["Oxigenación de la sangre"]
    N9_623 --> N11_695
    style N11_695 fill:#9cf,stroke:#333,stroke-width:2px
    N12_936["Eliminación de CO2"]
    N9_623 --> N12_936
    style N12_936 fill:#9cf,stroke:#333,stroke-width:2px
    N13_114["Mecanismos"]
    N1_485 --> N13_114
    style N13_114 fill:#ccf,stroke:#333,stroke-width:2px
    N14_807["Inspiración"]
    N13_114 --> N14_807
    style N14_807 fill:#9cf,stroke:#333,stroke-width:2px
    N15_474["Espiración"]
    N13_114 --> N15_474
    style N15_474 fill:#9cf,stroke:#333,stroke-width:2px
    N16_412["Control nervioso"]
    N13_114 --> N16_412
    style N16_412 fill:#9cf,stroke:#333,stroke-width:2px
    N17_414["Enfermedades"]
    N1_485 --> N17_414
    style N17_414 fill:#ccf,stroke:#333,stroke-width:2px
    N18_503["Asma"]
    N17_414 --> N18_503
    style N18_503 fill:#9cf,stroke:#333,stroke-width:2px
    N19_574["Bronquitis"]
    N17_414 --> N19_574
    style N19_574 fill:#9cf,stroke:#333,stroke-width:2px
    N20_667["Neumonía"]
    N17_414 --> N20_667
    style N20_667 fill:#9cf,stroke:#333,stroke-width:2px
    N21_154["EPOC"]
    N17_414 --> N21_154
    style N21_154 fill:#9cf,stroke:#333,stroke-width:2px
    N22_433["Factores de riesgo"]
    N1_485 --> N22_433
    style N22_433 fill:#ccf,stroke:#333,stroke-width:2px
    N23_601["Tabaquismo"]
    N22_433 --> N23_601
    style N23_601 fill:#9cf,stroke:#333,stroke-width:2px
    N24_932["Contaminación"]
    N22_433 --> N24_932
    style N24_932 fill:#9cf,stroke:#333,stroke-width:2px
    N25_526["Infecciones"]
    N22_433 --> N25_526
    style N25_526 fill:#9cf,stroke:#333,stroke-width:2px