graph LR
    N1_154["sistema respiratorio"]
    style N1_154 fill:#6366F1,stroke:#4F46E5,stroke-width:3px
    N2_100["Estructura"]
    N1_154 --> N2_100
    style N2_100 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N3_326["Nariz"]
    N2_100 --> N3_326
    style N3_326 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N4_350["Faringe"]
    N2_100 --> N4_350
    style N4_350 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N5_918["Laringe"]
    N2_100 --> N5_918
    style N5_918 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N6_256["Tráquea"]
    N2_100 --> N6_256
    style N6_256 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N7_994["Bronquios"]
    N2_100 --> N7_994
    style N7_994 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N8_983["Pulmones"]
    N2_100 --> N8_983
    style N8_983 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N9_595["Función"]
    N1_154 --> N9_595
    style N9_595 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N10_883["Intercambio de gases"]
    N9_595 --> N10_883
    style N10_883 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N11_118["Oxigenación de la sangre"]
    N9_595 --> N11_118
    style N11_118 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N12_573["Eliminación de CO2"]
    N9_595 --> N12_573
    style N12_573 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N13_495["Mecanismos"]
    N1_154 --> N13_495
    style N13_495 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N14_595["Inspiración"]
    N13_495 --> N14_595
    style N14_595 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N15_165["Espiración"]
    N13_495 --> N15_165
    style N15_165 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N16_434["Control nervioso"]
    N13_495 --> N16_434
    style N16_434 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N17_713["Enfermedades"]
    N1_154 --> N17_713
    style N17_713 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N18_799["Asma"]
    N17_713 --> N18_799
    style N18_799 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N19_919["Bronquitis"]
    N17_713 --> N19_919
    style N19_919 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N20_605["Neumonía"]
    N17_713 --> N20_605
    style N20_605 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N21_437["EPOC"]
    N17_713 --> N21_437
    style N21_437 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N22_465["Factores de riesgo"]
    N1_154 --> N22_465
    style N22_465 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N23_762["Tabaquismo"]
    N22_465 --> N23_762
    style N23_762 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N24_237["Contaminación"]
    N22_465 --> N24_237
    style N24_237 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N25_661["Infecciones"]
    N22_465 --> N25_661
    style N25_661 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px