graph LR
    N1_989["sistema respiratorio"]
    style N1_989 fill:#6366F1,stroke:#4F46E5,stroke-width:3px
    N2_566["Estructura"]
    N1_989 --> N2_566
    style N2_566 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N3_863["Nariz"]
    N2_566 --> N3_863
    style N3_863 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N4_811["Faringe"]
    N2_566 --> N4_811
    style N4_811 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N5_870["Laringe"]
    N2_566 --> N5_870
    style N5_870 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N6_904["Tráquea"]
    N2_566 --> N6_904
    style N6_904 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N7_295["Bronquios"]
    N2_566 --> N7_295
    style N7_295 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N8_507["Pulmones"]
    N2_566 --> N8_507
    style N8_507 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N9_202["Función"]
    N1_989 --> N9_202
    style N9_202 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N10_758["Intercambio de gases"]
    N9_202 --> N10_758
    style N10_758 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N11_659["Oxigenación de la sangre"]
    N9_202 --> N11_659
    style N11_659 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N12_639["Eliminación de CO2"]
    N9_202 --> N12_639
    style N12_639 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N13_312["Mecanismos"]
    N1_989 --> N13_312
    style N13_312 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N14_509["Inspiración"]
    N13_312 --> N14_509
    style N14_509 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N15_715["Espiración"]
    N13_312 --> N15_715
    style N15_715 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N16_641["Control nervioso"]
    N13_312 --> N16_641
    style N16_641 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N17_203["Enfermedades"]
    N1_989 --> N17_203
    style N17_203 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N18_726["Asma"]
    N17_203 --> N18_726
    style N18_726 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N19_502["Bronquitis"]
    N17_203 --> N19_502
    style N19_502 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N20_223["Neumonía"]
    N17_203 --> N20_223
    style N20_223 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N21_693["EPOC"]
    N17_203 --> N21_693
    style N21_693 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N22_910["Factores de riesgo"]
    N1_989 --> N22_910
    style N22_910 fill:#A5B4FC,stroke:#818CF8,stroke-width:2px
    N23_774["Tabaquismo"]
    N22_910 --> N23_774
    style N23_774 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N24_728["Contaminación"]
    N22_910 --> N24_728
    style N24_728 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px
    N25_375["Infecciones"]
    N22_910 --> N25_375
    style N25_375 fill:#DBEAFE,stroke:#93C5FD,stroke-width:2px