graph LR
    N1_158["sistema respiratorio"]
    style N1_158 fill:#f9f,stroke:#333,stroke-width:2px
    N2_937["Estructura"]
    N1_158 --> N2_937
    style N2_937 fill:#ccf,stroke:#333,stroke-width:2px
    N3_390["Nariz"]
    N2_937 --> N3_390
    style N3_390 fill:#9cf,stroke:#333,stroke-width:2px
    N4_867["Faringe"]
    N2_937 --> N4_867
    style N4_867 fill:#9cf,stroke:#333,stroke-width:2px
    N5_981["Laringe"]
    N2_937 --> N5_981
    style N5_981 fill:#9cf,stroke:#333,stroke-width:2px
    N6_475["Tráquea"]
    N2_937 --> N6_475
    style N6_475 fill:#9cf,stroke:#333,stroke-width:2px
    N7_498["Bronquios"]
    N2_937 --> N7_498
    style N7_498 fill:#9cf,stroke:#333,stroke-width:2px
    N8_851["Pulmones"]
    N2_937 --> N8_851
    style N8_851 fill:#9cf,stroke:#333,stroke-width:2px
    N9_259["Función"]
    N1_158 --> N9_259
    style N9_259 fill:#ccf,stroke:#333,stroke-width:2px
    N10_934["Intercambio de gases"]
    N9_259 --> N10_934
    style N10_934 fill:#9cf,stroke:#333,stroke-width:2px
    N11_231["Oxigenación de la sangre"]
    N9_259 --> N11_231
    style N11_231 fill:#9cf,stroke:#333,stroke-width:2px
    N12_429["Eliminación de CO2"]
    N9_259 --> N12_429
    style N12_429 fill:#9cf,stroke:#333,stroke-width:2px
    N13_426["Mecanismos"]
    N1_158 --> N13_426
    style N13_426 fill:#ccf,stroke:#333,stroke-width:2px
    N14_514["Inspiración"]
    N13_426 --> N14_514
    style N14_514 fill:#9cf,stroke:#333,stroke-width:2px
    N15_236["Espiración"]
    N13_426 --> N15_236
    style N15_236 fill:#9cf,stroke:#333,stroke-width:2px
    N16_940["Control nervioso"]
    N13_426 --> N16_940
    style N16_940 fill:#9cf,stroke:#333,stroke-width:2px
    N17_952["Enfermedades"]
    N1_158 --> N17_952
    style N17_952 fill:#ccf,stroke:#333,stroke-width:2px
    N18_173["Asma"]
    N17_952 --> N18_173
    style N18_173 fill:#9cf,stroke:#333,stroke-width:2px
    N19_687["Bronquitis"]
    N17_952 --> N19_687
    style N19_687 fill:#9cf,stroke:#333,stroke-width:2px
    N20_360["Neumonía"]
    N17_952 --> N20_360
    style N20_360 fill:#9cf,stroke:#333,stroke-width:2px
    N21_891["EPOC"]
    N17_952 --> N21_891
    style N21_891 fill:#9cf,stroke:#333,stroke-width:2px
    N22_928["Factores de riesgo"]
    N1_158 --> N22_928
    style N22_928 fill:#ccf,stroke:#333,stroke-width:2px
    N23_105["Tabaquismo"]
    N22_928 --> N23_105
    style N23_105 fill:#9cf,stroke:#333,stroke-width:2px
    N24_595["Contaminación"]
    N22_928 --> N24_595
    style N24_595 fill:#9cf,stroke:#333,stroke-width:2px
    N25_683["Infecciones"]
    N22_928 --> N25_683
    style N25_683 fill:#9cf,stroke:#333,stroke-width:2px