graph LR
    N1_450["sistema respiratorio"]
    style N1_450 fill:#f9f,stroke:#333,stroke-width:2px
    N2_707["Estructura"]
    N1_450 --> N2_707
    style N2_707 fill:#ccf,stroke:#333,stroke-width:2px
    N3_375["Nariz"]
    N2_707 --> N3_375
    style N3_375 fill:#9cf,stroke:#333,stroke-width:2px
    N4_572["Faringe"]
    N2_707 --> N4_572
    style N4_572 fill:#9cf,stroke:#333,stroke-width:2px
    N5_596["Laringe"]
    N2_707 --> N5_596
    style N5_596 fill:#9cf,stroke:#333,stroke-width:2px
    N6_489["Tráquea"]
    N2_707 --> N6_489
    style N6_489 fill:#9cf,stroke:#333,stroke-width:2px
    N7_147["Bronquios"]
    N2_707 --> N7_147
    style N7_147 fill:#9cf,stroke:#333,stroke-width:2px
    N8_586["Pulmones"]
    N2_707 --> N8_586
    style N8_586 fill:#9cf,stroke:#333,stroke-width:2px
    N9_349["Función"]
    N1_450 --> N9_349
    style N9_349 fill:#ccf,stroke:#333,stroke-width:2px
    N10_491["Intercambio de gases"]
    N9_349 --> N10_491
    style N10_491 fill:#9cf,stroke:#333,stroke-width:2px
    N11_426["Oxigenación de la sangre"]
    N9_349 --> N11_426
    style N11_426 fill:#9cf,stroke:#333,stroke-width:2px
    N12_618["Eliminación de CO2"]
    N9_349 --> N12_618
    style N12_618 fill:#9cf,stroke:#333,stroke-width:2px
    N13_839["Mecanismos"]
    N1_450 --> N13_839
    style N13_839 fill:#ccf,stroke:#333,stroke-width:2px
    N14_106["Inspiración"]
    N13_839 --> N14_106
    style N14_106 fill:#9cf,stroke:#333,stroke-width:2px
    N15_415["Espiración"]
    N13_839 --> N15_415
    style N15_415 fill:#9cf,stroke:#333,stroke-width:2px
    N16_167["Control nervioso"]
    N13_839 --> N16_167
    style N16_167 fill:#9cf,stroke:#333,stroke-width:2px
    N17_939["Enfermedades"]
    N1_450 --> N17_939
    style N17_939 fill:#ccf,stroke:#333,stroke-width:2px
    N18_911["Asma"]
    N17_939 --> N18_911
    style N18_911 fill:#9cf,stroke:#333,stroke-width:2px
    N19_888["Bronquitis"]
    N17_939 --> N19_888
    style N19_888 fill:#9cf,stroke:#333,stroke-width:2px
    N20_831["Neumonía"]
    N17_939 --> N20_831
    style N20_831 fill:#9cf,stroke:#333,stroke-width:2px
    N21_614["EPOC"]
    N17_939 --> N21_614
    style N21_614 fill:#9cf,stroke:#333,stroke-width:2px
    N22_823["Factores de riesgo"]
    N1_450 --> N22_823
    style N22_823 fill:#ccf,stroke:#333,stroke-width:2px
    N23_389["Tabaquismo"]
    N22_823 --> N23_389
    style N23_389 fill:#9cf,stroke:#333,stroke-width:2px
    N24_852["Contaminación"]
    N22_823 --> N24_852
    style N24_852 fill:#9cf,stroke:#333,stroke-width:2px
    N25_359["Infecciones"]
    N22_823 --> N25_359
    style N25_359 fill:#9cf,stroke:#333,stroke-width:2px