name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check syntax of project files
      run: |
        python3 check_syntax.py
    
    - name: Run limited flake8 (project files only)
      run: |
        pip install flake8
        # Solo verificar nuestros archivos, no las librerías externas
        flake8 mi_app_estudio/ backend/ *.py --exclude=__pycache__,.venv,venv --max-line-length=120 --ignore=E501,W291,W293,W391,F401
      continue-on-error: true
    
    - name: Test basic imports
      run: |
        python3 -c "
        try:
            import mi_app_estudio.mi_app_estudio
            import mi_app_estudio.state
            import backend.config_logic
            print('✅ All main modules import successfully')
        except Exception as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "
      continue-on-error: true
